version: '3.7'

services:
  hebcal-web:
    container_name: hebcal-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

