// source: download.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.Download', null, global);
goog.exportSymbol('proto.Download.EndOneofCase', null, global);
goog.exportSymbol('proto.Download.Hour12', null, global);
goog.exportSymbol('proto.Download.LatOneofCase', null, global);
goog.exportSymbol('proto.Download.LongOneofCase', null, global);
goog.exportSymbol('proto.Download.StartOneofCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Download = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.Download.oneofGroups_);
};
goog.inherits(proto.Download, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Download.displayName = 'proto.Download';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.Download.oneofGroups_ = [[32,41],[33,42],[35,43],[36,44]];

/**
 * @enum {number}
 */
proto.Download.LatOneofCase = {
  LAT_ONEOF_NOT_SET: 0,
  OLD_LATITUDE: 32,
  LATITUDE: 41
};

/**
 * @return {proto.Download.LatOneofCase}
 */
proto.Download.prototype.getLatOneofCase = function() {
  return /** @type {proto.Download.LatOneofCase} */(jspb.Message.computeOneofCase(this, proto.Download.oneofGroups_[0]));
};

/**
 * @enum {number}
 */
proto.Download.LongOneofCase = {
  LONG_ONEOF_NOT_SET: 0,
  OLD_LONGITUDE: 33,
  LONGITUDE: 42
};

/**
 * @return {proto.Download.LongOneofCase}
 */
proto.Download.prototype.getLongOneofCase = function() {
  return /** @type {proto.Download.LongOneofCase} */(jspb.Message.computeOneofCase(this, proto.Download.oneofGroups_[1]));
};

/**
 * @enum {number}
 */
proto.Download.StartOneofCase = {
  START_ONEOF_NOT_SET: 0,
  START_STR: 35,
  START: 43
};

/**
 * @return {proto.Download.StartOneofCase}
 */
proto.Download.prototype.getStartOneofCase = function() {
  return /** @type {proto.Download.StartOneofCase} */(jspb.Message.computeOneofCase(this, proto.Download.oneofGroups_[2]));
};

/**
 * @enum {number}
 */
proto.Download.EndOneofCase = {
  END_ONEOF_NOT_SET: 0,
  END_STR: 36,
  END: 44
};

/**
 * @return {proto.Download.EndOneofCase}
 */
proto.Download.prototype.getEndOneofCase = function() {
  return /** @type {proto.Download.EndOneofCase} */(jspb.Message.computeOneofCase(this, proto.Download.oneofGroups_[3]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Download.prototype.toObject = function(opt_includeInstance) {
  return proto.Download.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Download} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Download.toObject = function(includeInstance, msg) {
  var f, obj = {
    major: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    minor: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    roshchodesh: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    modern: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    minorfast: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    specialshabbat: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    israel: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    havdalahtzeit: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    ishebrewyear: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    candlelighting: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    geonameid: jspb.Message.getFieldWithDefault(msg, 11, 0),
    year: jspb.Message.getFieldWithDefault(msg, 12, 0),
    locale: jspb.Message.getFieldWithDefault(msg, 13, ""),
    havdalahmins: jspb.Message.getFieldWithDefault(msg, 14, 0),
    candlelightingmins: jspb.Message.getFieldWithDefault(msg, 15, 0),
    emoji: jspb.Message.getBooleanFieldWithDefault(msg, 16, false),
    sedrot: jspb.Message.getBooleanFieldWithDefault(msg, 17, false),
    zip: jspb.Message.getFieldWithDefault(msg, 18, ""),
    yearnow: jspb.Message.getBooleanFieldWithDefault(msg, 19, false),
    subscribe: jspb.Message.getBooleanFieldWithDefault(msg, 20, false),
    addhebrewdates: jspb.Message.getBooleanFieldWithDefault(msg, 23, false),
    addhebrewdatesforevents: jspb.Message.getBooleanFieldWithDefault(msg, 24, false),
    omer: jspb.Message.getBooleanFieldWithDefault(msg, 25, false),
    dafyomi: jspb.Message.getBooleanFieldWithDefault(msg, 26, false),
    euro: jspb.Message.getBooleanFieldWithDefault(msg, 27, false),
    mishnayomi: jspb.Message.getBooleanFieldWithDefault(msg, 28, false),
    geopos: jspb.Message.getBooleanFieldWithDefault(msg, 29, false),
    month: jspb.Message.getFieldWithDefault(msg, 30, 0),
    numyears: jspb.Message.getFieldWithDefault(msg, 31, 0),
    oldLatitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 32, 0.0),
    latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 41, 0.0),
    oldLongitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 33, 0.0),
    longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 42, 0.0),
    tzid: jspb.Message.getFieldWithDefault(msg, 34, ""),
    startStr: jspb.Message.getFieldWithDefault(msg, 35, ""),
    start: jspb.Message.getFieldWithDefault(msg, 43, 0),
    endStr: jspb.Message.getFieldWithDefault(msg, 36, ""),
    end: jspb.Message.getFieldWithDefault(msg, 44, 0),
    yomkippurkatan: jspb.Message.getBooleanFieldWithDefault(msg, 37, false),
    hour12: jspb.Message.getFieldWithDefault(msg, 39, 0),
    cityname: jspb.Message.getFieldWithDefault(msg, 40, ""),
    yerushalmiyomi: jspb.Message.getBooleanFieldWithDefault(msg, 45, false),
    nachyomi: jspb.Message.getBooleanFieldWithDefault(msg, 46, false),
    rambam1: jspb.Message.getBooleanFieldWithDefault(msg, 47, false),
    chofetzchaim: jspb.Message.getBooleanFieldWithDefault(msg, 48, false),
    shemirathalashon: jspb.Message.getBooleanFieldWithDefault(msg, 49, false),
    psalms: jspb.Message.getBooleanFieldWithDefault(msg, 50, false),
    dafweekly: jspb.Message.getBooleanFieldWithDefault(msg, 51, false),
    elev: jspb.Message.getFieldWithDefault(msg, 52, 0),
    useelevation: jspb.Message.getBooleanFieldWithDefault(msg, 53, false),
    tanakhyomi: jspb.Message.getBooleanFieldWithDefault(msg, 54, false),
    pirkeiavotsummer: jspb.Message.getBooleanFieldWithDefault(msg, 55, false),
    yizkor: jspb.Message.getBooleanFieldWithDefault(msg, 56, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Download}
 */
proto.Download.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Download;
  return proto.Download.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Download} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Download}
 */
proto.Download.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMajor(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMinor(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRoshchodesh(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setModern(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMinorfast(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSpecialshabbat(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsrael(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHavdalahtzeit(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIshebrewyear(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCandlelighting(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGeonameid(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setYear(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocale(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHavdalahmins(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCandlelightingmins(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEmoji(value);
      break;
    case 17:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSedrot(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setZip(value);
      break;
    case 19:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setYearnow(value);
      break;
    case 20:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSubscribe(value);
      break;
    case 23:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAddhebrewdates(value);
      break;
    case 24:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAddhebrewdatesforevents(value);
      break;
    case 25:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOmer(value);
      break;
    case 26:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDafyomi(value);
      break;
    case 27:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEuro(value);
      break;
    case 28:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMishnayomi(value);
      break;
    case 29:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGeopos(value);
      break;
    case 30:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMonth(value);
      break;
    case 31:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumyears(value);
      break;
    case 32:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOldLatitude(value);
      break;
    case 41:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLatitude(value);
      break;
    case 33:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOldLongitude(value);
      break;
    case 42:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLongitude(value);
      break;
    case 34:
      var value = /** @type {string} */ (reader.readString());
      msg.setTzid(value);
      break;
    case 35:
      var value = /** @type {string} */ (reader.readString());
      msg.setStartStr(value);
      break;
    case 43:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStart(value);
      break;
    case 36:
      var value = /** @type {string} */ (reader.readString());
      msg.setEndStr(value);
      break;
    case 44:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEnd(value);
      break;
    case 37:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setYomkippurkatan(value);
      break;
    case 39:
      var value = /** @type {!proto.Download.Hour12} */ (reader.readEnum());
      msg.setHour12(value);
      break;
    case 40:
      var value = /** @type {string} */ (reader.readString());
      msg.setCityname(value);
      break;
    case 45:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setYerushalmiyomi(value);
      break;
    case 46:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNachyomi(value);
      break;
    case 47:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRambam1(value);
      break;
    case 48:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setChofetzchaim(value);
      break;
    case 49:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShemirathalashon(value);
      break;
    case 50:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPsalms(value);
      break;
    case 51:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDafweekly(value);
      break;
    case 52:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setElev(value);
      break;
    case 53:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setUseelevation(value);
      break;
    case 54:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTanakhyomi(value);
      break;
    case 55:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPirkeiavotsummer(value);
      break;
    case 56:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setYizkor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Download.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Download.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Download} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Download.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMajor();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMinor();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getRoshchodesh();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getModern();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getMinorfast();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getSpecialshabbat();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getIsrael();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getHavdalahtzeit();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getIshebrewyear();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getCandlelighting();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getGeonameid();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getYear();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getLocale();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getHavdalahmins();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getCandlelightingmins();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
  f = message.getEmoji();
  if (f) {
    writer.writeBool(
      16,
      f
    );
  }
  f = message.getSedrot();
  if (f) {
    writer.writeBool(
      17,
      f
    );
  }
  f = message.getZip();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getYearnow();
  if (f) {
    writer.writeBool(
      19,
      f
    );
  }
  f = message.getSubscribe();
  if (f) {
    writer.writeBool(
      20,
      f
    );
  }
  f = message.getAddhebrewdates();
  if (f) {
    writer.writeBool(
      23,
      f
    );
  }
  f = message.getAddhebrewdatesforevents();
  if (f) {
    writer.writeBool(
      24,
      f
    );
  }
  f = message.getOmer();
  if (f) {
    writer.writeBool(
      25,
      f
    );
  }
  f = message.getDafyomi();
  if (f) {
    writer.writeBool(
      26,
      f
    );
  }
  f = message.getEuro();
  if (f) {
    writer.writeBool(
      27,
      f
    );
  }
  f = message.getMishnayomi();
  if (f) {
    writer.writeBool(
      28,
      f
    );
  }
  f = message.getGeopos();
  if (f) {
    writer.writeBool(
      29,
      f
    );
  }
  f = message.getMonth();
  if (f !== 0) {
    writer.writeInt32(
      30,
      f
    );
  }
  f = message.getNumyears();
  if (f !== 0) {
    writer.writeInt32(
      31,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 32));
  if (f != null) {
    writer.writeDouble(
      32,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 41));
  if (f != null) {
    writer.writeFloat(
      41,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 33));
  if (f != null) {
    writer.writeDouble(
      33,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 42));
  if (f != null) {
    writer.writeFloat(
      42,
      f
    );
  }
  f = message.getTzid();
  if (f.length > 0) {
    writer.writeString(
      34,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 35));
  if (f != null) {
    writer.writeString(
      35,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 43));
  if (f != null) {
    writer.writeInt64(
      43,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 36));
  if (f != null) {
    writer.writeString(
      36,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 44));
  if (f != null) {
    writer.writeInt64(
      44,
      f
    );
  }
  f = message.getYomkippurkatan();
  if (f) {
    writer.writeBool(
      37,
      f
    );
  }
  f = message.getHour12();
  if (f !== 0.0) {
    writer.writeEnum(
      39,
      f
    );
  }
  f = message.getCityname();
  if (f.length > 0) {
    writer.writeString(
      40,
      f
    );
  }
  f = message.getYerushalmiyomi();
  if (f) {
    writer.writeBool(
      45,
      f
    );
  }
  f = message.getNachyomi();
  if (f) {
    writer.writeBool(
      46,
      f
    );
  }
  f = message.getRambam1();
  if (f) {
    writer.writeBool(
      47,
      f
    );
  }
  f = message.getChofetzchaim();
  if (f) {
    writer.writeBool(
      48,
      f
    );
  }
  f = message.getShemirathalashon();
  if (f) {
    writer.writeBool(
      49,
      f
    );
  }
  f = message.getPsalms();
  if (f) {
    writer.writeBool(
      50,
      f
    );
  }
  f = message.getDafweekly();
  if (f) {
    writer.writeBool(
      51,
      f
    );
  }
  f = message.getElev();
  if (f !== 0) {
    writer.writeInt32(
      52,
      f
    );
  }
  f = message.getUseelevation();
  if (f) {
    writer.writeBool(
      53,
      f
    );
  }
  f = message.getTanakhyomi();
  if (f) {
    writer.writeBool(
      54,
      f
    );
  }
  f = message.getPirkeiavotsummer();
  if (f) {
    writer.writeBool(
      55,
      f
    );
  }
  f = message.getYizkor();
  if (f) {
    writer.writeBool(
      56,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.Download.Hour12 = {
  UNSET: 0,
  ON: 1,
  OFF: 2
};

/**
 * optional bool major = 1;
 * @return {boolean}
 */
proto.Download.prototype.getMajor = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setMajor = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool minor = 2;
 * @return {boolean}
 */
proto.Download.prototype.getMinor = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setMinor = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool roshChodesh = 3;
 * @return {boolean}
 */
proto.Download.prototype.getRoshchodesh = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setRoshchodesh = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool modern = 4;
 * @return {boolean}
 */
proto.Download.prototype.getModern = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setModern = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool minorFast = 5;
 * @return {boolean}
 */
proto.Download.prototype.getMinorfast = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setMinorfast = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool specialShabbat = 6;
 * @return {boolean}
 */
proto.Download.prototype.getSpecialshabbat = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setSpecialshabbat = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool israel = 7;
 * @return {boolean}
 */
proto.Download.prototype.getIsrael = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setIsrael = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool havdalahTzeit = 8;
 * @return {boolean}
 */
proto.Download.prototype.getHavdalahtzeit = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setHavdalahtzeit = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool isHebrewYear = 9;
 * @return {boolean}
 */
proto.Download.prototype.getIshebrewyear = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setIshebrewyear = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool candlelighting = 10;
 * @return {boolean}
 */
proto.Download.prototype.getCandlelighting = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setCandlelighting = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional int32 geonameid = 11;
 * @return {number}
 */
proto.Download.prototype.getGeonameid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setGeonameid = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 year = 12;
 * @return {number}
 */
proto.Download.prototype.getYear = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setYear = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string locale = 13;
 * @return {string}
 */
proto.Download.prototype.getLocale = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setLocale = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional int32 havdalahMins = 14;
 * @return {number}
 */
proto.Download.prototype.getHavdalahmins = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setHavdalahmins = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional int32 candleLightingMins = 15;
 * @return {number}
 */
proto.Download.prototype.getCandlelightingmins = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setCandlelightingmins = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional bool emoji = 16;
 * @return {boolean}
 */
proto.Download.prototype.getEmoji = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 16, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setEmoji = function(value) {
  return jspb.Message.setProto3BooleanField(this, 16, value);
};


/**
 * optional bool sedrot = 17;
 * @return {boolean}
 */
proto.Download.prototype.getSedrot = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 17, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setSedrot = function(value) {
  return jspb.Message.setProto3BooleanField(this, 17, value);
};


/**
 * optional string zip = 18;
 * @return {string}
 */
proto.Download.prototype.getZip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setZip = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional bool yearNow = 19;
 * @return {boolean}
 */
proto.Download.prototype.getYearnow = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 19, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setYearnow = function(value) {
  return jspb.Message.setProto3BooleanField(this, 19, value);
};


/**
 * optional bool subscribe = 20;
 * @return {boolean}
 */
proto.Download.prototype.getSubscribe = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 20, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setSubscribe = function(value) {
  return jspb.Message.setProto3BooleanField(this, 20, value);
};


/**
 * optional bool addHebrewDates = 23;
 * @return {boolean}
 */
proto.Download.prototype.getAddhebrewdates = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 23, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setAddhebrewdates = function(value) {
  return jspb.Message.setProto3BooleanField(this, 23, value);
};


/**
 * optional bool addHebrewDatesForEvents = 24;
 * @return {boolean}
 */
proto.Download.prototype.getAddhebrewdatesforevents = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 24, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setAddhebrewdatesforevents = function(value) {
  return jspb.Message.setProto3BooleanField(this, 24, value);
};


/**
 * optional bool omer = 25;
 * @return {boolean}
 */
proto.Download.prototype.getOmer = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 25, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setOmer = function(value) {
  return jspb.Message.setProto3BooleanField(this, 25, value);
};


/**
 * optional bool dafyomi = 26;
 * @return {boolean}
 */
proto.Download.prototype.getDafyomi = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 26, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setDafyomi = function(value) {
  return jspb.Message.setProto3BooleanField(this, 26, value);
};


/**
 * optional bool euro = 27;
 * @return {boolean}
 */
proto.Download.prototype.getEuro = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 27, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setEuro = function(value) {
  return jspb.Message.setProto3BooleanField(this, 27, value);
};


/**
 * optional bool mishnaYomi = 28;
 * @return {boolean}
 */
proto.Download.prototype.getMishnayomi = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 28, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setMishnayomi = function(value) {
  return jspb.Message.setProto3BooleanField(this, 28, value);
};


/**
 * optional bool geoPos = 29;
 * @return {boolean}
 */
proto.Download.prototype.getGeopos = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 29, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setGeopos = function(value) {
  return jspb.Message.setProto3BooleanField(this, 29, value);
};


/**
 * optional int32 month = 30;
 * @return {number}
 */
proto.Download.prototype.getMonth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 30, 0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setMonth = function(value) {
  return jspb.Message.setProto3IntField(this, 30, value);
};


/**
 * optional int32 numYears = 31;
 * @return {number}
 */
proto.Download.prototype.getNumyears = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 31, 0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setNumyears = function(value) {
  return jspb.Message.setProto3IntField(this, 31, value);
};


/**
 * optional double old_latitude = 32;
 * @return {number}
 */
proto.Download.prototype.getOldLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 32, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setOldLatitude = function(value) {
  return jspb.Message.setOneofField(this, 32, proto.Download.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.clearOldLatitude = function() {
  return jspb.Message.setOneofField(this, 32, proto.Download.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Download.prototype.hasOldLatitude = function() {
  return jspb.Message.getField(this, 32) != null;
};


/**
 * optional float latitude = 41;
 * @return {number}
 */
proto.Download.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 41, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setLatitude = function(value) {
  return jspb.Message.setOneofField(this, 41, proto.Download.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.clearLatitude = function() {
  return jspb.Message.setOneofField(this, 41, proto.Download.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Download.prototype.hasLatitude = function() {
  return jspb.Message.getField(this, 41) != null;
};


/**
 * optional double old_longitude = 33;
 * @return {number}
 */
proto.Download.prototype.getOldLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 33, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setOldLongitude = function(value) {
  return jspb.Message.setOneofField(this, 33, proto.Download.oneofGroups_[1], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.clearOldLongitude = function() {
  return jspb.Message.setOneofField(this, 33, proto.Download.oneofGroups_[1], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Download.prototype.hasOldLongitude = function() {
  return jspb.Message.getField(this, 33) != null;
};


/**
 * optional float longitude = 42;
 * @return {number}
 */
proto.Download.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 42, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setLongitude = function(value) {
  return jspb.Message.setOneofField(this, 42, proto.Download.oneofGroups_[1], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.clearLongitude = function() {
  return jspb.Message.setOneofField(this, 42, proto.Download.oneofGroups_[1], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Download.prototype.hasLongitude = function() {
  return jspb.Message.getField(this, 42) != null;
};


/**
 * optional string tzid = 34;
 * @return {string}
 */
proto.Download.prototype.getTzid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 34, ""));
};


/**
 * @param {string} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setTzid = function(value) {
  return jspb.Message.setProto3StringField(this, 34, value);
};


/**
 * optional string start_str = 35;
 * @return {string}
 */
proto.Download.prototype.getStartStr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 35, ""));
};


/**
 * @param {string} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setStartStr = function(value) {
  return jspb.Message.setOneofField(this, 35, proto.Download.oneofGroups_[2], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.clearStartStr = function() {
  return jspb.Message.setOneofField(this, 35, proto.Download.oneofGroups_[2], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Download.prototype.hasStartStr = function() {
  return jspb.Message.getField(this, 35) != null;
};


/**
 * optional int64 start = 43;
 * @return {number}
 */
proto.Download.prototype.getStart = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 43, 0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setStart = function(value) {
  return jspb.Message.setOneofField(this, 43, proto.Download.oneofGroups_[2], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.clearStart = function() {
  return jspb.Message.setOneofField(this, 43, proto.Download.oneofGroups_[2], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Download.prototype.hasStart = function() {
  return jspb.Message.getField(this, 43) != null;
};


/**
 * optional string end_str = 36;
 * @return {string}
 */
proto.Download.prototype.getEndStr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 36, ""));
};


/**
 * @param {string} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setEndStr = function(value) {
  return jspb.Message.setOneofField(this, 36, proto.Download.oneofGroups_[3], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.clearEndStr = function() {
  return jspb.Message.setOneofField(this, 36, proto.Download.oneofGroups_[3], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Download.prototype.hasEndStr = function() {
  return jspb.Message.getField(this, 36) != null;
};


/**
 * optional int64 end = 44;
 * @return {number}
 */
proto.Download.prototype.getEnd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 44, 0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setEnd = function(value) {
  return jspb.Message.setOneofField(this, 44, proto.Download.oneofGroups_[3], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.clearEnd = function() {
  return jspb.Message.setOneofField(this, 44, proto.Download.oneofGroups_[3], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Download.prototype.hasEnd = function() {
  return jspb.Message.getField(this, 44) != null;
};


/**
 * optional bool yomKippurKatan = 37;
 * @return {boolean}
 */
proto.Download.prototype.getYomkippurkatan = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 37, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setYomkippurkatan = function(value) {
  return jspb.Message.setProto3BooleanField(this, 37, value);
};


/**
 * optional Hour12 hour12 = 39;
 * @return {!proto.Download.Hour12}
 */
proto.Download.prototype.getHour12 = function() {
  return /** @type {!proto.Download.Hour12} */ (jspb.Message.getFieldWithDefault(this, 39, 0));
};


/**
 * @param {!proto.Download.Hour12} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setHour12 = function(value) {
  return jspb.Message.setProto3EnumField(this, 39, value);
};


/**
 * optional string cityName = 40;
 * @return {string}
 */
proto.Download.prototype.getCityname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 40, ""));
};


/**
 * @param {string} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setCityname = function(value) {
  return jspb.Message.setProto3StringField(this, 40, value);
};


/**
 * optional bool yerushalmiYomi = 45;
 * @return {boolean}
 */
proto.Download.prototype.getYerushalmiyomi = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 45, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setYerushalmiyomi = function(value) {
  return jspb.Message.setProto3BooleanField(this, 45, value);
};


/**
 * optional bool nachYomi = 46;
 * @return {boolean}
 */
proto.Download.prototype.getNachyomi = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 46, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setNachyomi = function(value) {
  return jspb.Message.setProto3BooleanField(this, 46, value);
};


/**
 * optional bool rambam1 = 47;
 * @return {boolean}
 */
proto.Download.prototype.getRambam1 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 47, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setRambam1 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 47, value);
};


/**
 * optional bool chofetzChaim = 48;
 * @return {boolean}
 */
proto.Download.prototype.getChofetzchaim = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 48, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setChofetzchaim = function(value) {
  return jspb.Message.setProto3BooleanField(this, 48, value);
};


/**
 * optional bool shemiratHaLashon = 49;
 * @return {boolean}
 */
proto.Download.prototype.getShemirathalashon = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 49, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setShemirathalashon = function(value) {
  return jspb.Message.setProto3BooleanField(this, 49, value);
};


/**
 * optional bool psalms = 50;
 * @return {boolean}
 */
proto.Download.prototype.getPsalms = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 50, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setPsalms = function(value) {
  return jspb.Message.setProto3BooleanField(this, 50, value);
};


/**
 * optional bool dafWeekly = 51;
 * @return {boolean}
 */
proto.Download.prototype.getDafweekly = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 51, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setDafweekly = function(value) {
  return jspb.Message.setProto3BooleanField(this, 51, value);
};


/**
 * optional int32 elev = 52;
 * @return {number}
 */
proto.Download.prototype.getElev = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 52, 0));
};


/**
 * @param {number} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setElev = function(value) {
  return jspb.Message.setProto3IntField(this, 52, value);
};


/**
 * optional bool useElevation = 53;
 * @return {boolean}
 */
proto.Download.prototype.getUseelevation = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 53, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setUseelevation = function(value) {
  return jspb.Message.setProto3BooleanField(this, 53, value);
};


/**
 * optional bool tanakhYomi = 54;
 * @return {boolean}
 */
proto.Download.prototype.getTanakhyomi = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 54, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setTanakhyomi = function(value) {
  return jspb.Message.setProto3BooleanField(this, 54, value);
};


/**
 * optional bool pirkeiAvotSummer = 55;
 * @return {boolean}
 */
proto.Download.prototype.getPirkeiavotsummer = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 55, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setPirkeiavotsummer = function(value) {
  return jspb.Message.setProto3BooleanField(this, 55, value);
};


/**
 * optional bool yizkor = 56;
 * @return {boolean}
 */
proto.Download.prototype.getYizkor = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 56, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Download} returns this
 */
proto.Download.prototype.setYizkor = function(value) {
  return jspb.Message.setProto3BooleanField(this, 56, value);
};


goog.object.extend(exports, proto);
